# docker-compose.yml
version: "3"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: application
    container_name: application
    restart: unless-stopped
    env_file: .env
    ports:
      - 5050:$PORT
    volumes:
      - ./src:/home/app/src
    networks:
      - network
    command: ./wait-for-it.sh database:5432 -- pm2-runtime src/index.js
    depends_on:
      - database

  database:
    image: postgres:12.3-alpine
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: wishpass
      POSTGRES_USER: wishuser
      POSTGRES_DB: wishdb
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  pgdata:
