# docker-compose.yml
version: "3"

services:
  whishlist_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whishlist_app
    container_name: whishlist_app
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=${PORT}
      - DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@whishlist_db:5432/${DB_NAME}
    ports:
      - 5050:$PORT
    volumes:
      - ./src:/home/whishlist/src
    networks:
      - whishlist-network
    command: ./wait-for-it.sh whishlist_db:5432 -- pm2-runtime src/index.js

  whishlist_db:
    image: postgres:12.3-alpine
    container_name: whishlist_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - whishlist-network

networks:
  whishlist-network:
    driver: bridge
