# docker-compose.yml
version: "3"

services:
  whishlist_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whishlist_app
    container_name: whishlist_app
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=${PORT}
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@whishlist_db:5432/${POSTGRES_DB}
    ports:
      - 5050:$PORT
    volumes:
      - ./src:/home/whishlist/src
    networks:
      - whishlist-network
    command: ./wait-for-it.sh whishlist_db:5432 -- pm2-runtime src/index.js
    depends_on:
      - whishlist_db

  whishlist_db:
    image: postgres:12.3-alpine
    container_name: whishlist_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - whishlist-network

networks:
  whishlist-network:
    driver: bridge

volumes:
  pgdata:
